language: node_js
cache:
  directories:
  - node_modules
node_js:
- '0.12.3'
env:
  global:
  - GH_REF: github.com/akirasosa/react-chat
  # GH_TOKEN
  - secure: qHG1Uj3aZErFNxgwuXsp8HzHLnGEmtcMoyzMH02ooXLgXE7oevTQBy5fnZFMaR8n6VmllybWCrTI5lm9+DtiIstoSnSGioOF1DbH+pM9p2NYICGG7PmbO5pC6x0+5ZpeBjIEBErhSq5wXfOLOScHvM8vWLS000uCllHkBbjXIyLHJEHmoPeIkCi7l1iV1XPb3Hrc8Kc5MnopwmvV0KN9MSR0eTlk6eNTt88i+ofITQ6b3BnYWRJ/+cR6gblFPz4lozFuNIxcMd3Xuyl7qzzWndE6oerP9k5UBMMxvBVrJFw2uezj6u1LgH4WDgBIbeA5moIDmvhQNGoSLpKnRka/136TBqVqlfZ+XZsacLaR5QMERNFN9aIjDK3ohPnypIIptV4NQz6d1lv/14+mZNTOWJwgGy8NAbJ3QWiM7ze5+w1yFhhio8c5zEUk5C8cUTLF3SE/qu5q6+4bDnC1jb2ZNstrBsb/pzMssQ52rkQa1HzAb2EVZbpYOfcjftEKbMWZy/R1TXUwMtfVWOBkpm0ZqU5awOIW2TgjbHTLdYBDOXm5YdTOHwQ0lRkG1qwTS4o4i6hHYv2ipedyGbROxjcAfq/G7NcDkuDzmo3ExbXUBZ02tiHUrX3IwhSjSlRiqzS809MahCvBdNQ2ppcM3R9WgJT+UszTCb53wb/gsPY+trg=
script:
- echo 1
after_success:
- scripts/push-to-ghpages.sh
