language: node_js
cache:
  directories:
  - node_modules
node_js:
- '0.12.3'
env:
  global:
  - GH_REF: github.com/akirasosa/react-chat
  # GH_TOKEN
  - secure: "M9N1kgLAxrth1IJr9TT0PJyZ/OFEf5FrCXX1DaM5TC5rK2R0HjBRuXoIXO+NwenRLcofNssYuSSllGgFR48lNkZKbF2GBbtEc1O+V+r7sjzRk9NQ4cfpl8s1wSJMPeuQa+86w6R6BCZDnYws/SEcODcUasAxs11hxcKaT1mvVxFV33RU7E4y0X9E6Y+3f0pH5NBF5tDqpHihvrlMAUoAm61ZcsJmKl8H92oGCzgeEE7zB8H9GIeYNEJ//uQWliT56+eQ9a0RYR9pTT2BkReiXQ1xUgyyIsdgkcKOZgbD3uPdVYWjBQHX1xZm81j3r//YREmjL7zJpAPTw5qfyEioc18BCOwmrtsAMfkpJcbaTkmJEpgKzERyyzv1H49KFoK59VRSDmiUVcmTpOBiguzerAeDYq2+uEEdpkTg0wEOIc0mXlBxNThPzV/kTNDBIIj9XRDmOb3CHzdXkLeUumV+4jAZLYBTDZSm74mMNrCwR94asvMTnJKXu2EaQec0CdEbazVjDNVrIbMlw1GxmwExIgFz4VAS6wz9aA+srdgmu+/jqe4WzKzkOKmlYUmhaW+osdMqVJm7IWtlj5/BWbW16tRUiwUV/L5qCtU81hLtnzSmYq/2OWWiTg04lLx+/e2uUqIyGpI5mXaJr6P1oGSx8RMutW3b0EgreXvomRWoAks="
script:
- echo 1
after_success:
- scripts/push-to-ghpages.sh
